/* Add AUTHENTICATED Column to CONNECTED_CLOUDS */
declare column_exists exception;
pragma exception_init(column_exists,-01430);
begin execute immediate 
'ALTER TABLE CONNECTED_CLOUDS
ADD (AUTHENTICATED NUMBER)';
exception when column_exists then null;
end;
/ 
COMMENT ON COLUMN 
"INTERCLOUD"."CONNECTED_CLOUDS"."AUTHENTICATED" is 
'Authenticated or not. 0 if authenticated.';
/

/* New Request and Result Track */
CREATE TABLE REQUEST_TRACK 
      (
        ID NUMBER NOT NULL 
      , TARGET_CLOUD VARCHAR2(128) NOT NULL 
      , REQUEST LONG 
      , LAST_UPDATE DATE 
      , CONSTRAINT REQUEST_TRACK_PK PRIMARY KEY 
        (
          ID 
        )
        ENABLE 
      );
/
COMMENT ON TABLE "INTERCLOUD"."REQUEST_TRACK"  is 'Tracks the requests.';
/
COMMENT ON COLUMN REQUEST_TRACK.ID IS 'The request ID';
COMMENT ON COLUMN REQUEST_TRACK.TARGET_CLOUD IS 'The target cloud';
COMMENT ON COLUMN REQUEST_TRACK.REQUEST IS 'The request message';
COMMENT ON COLUMN REQUEST_TRACK.LAST_UPDATE IS 'Last update time of the record, auto updated';
/

CREATE TABLE RESULT_TRACK 
      (
        ID NUMBER NOT NULL 
      , TARGET_CLOUD VARCHAR2(128) NOT NULL 
      , RESULT LONG 
      , LAST_UPDATE DATE 
      , CONSTRAINT RESULT_TRACK_PK PRIMARY KEY 
        (
          ID 
        )
        ENABLE 
      );
/
COMMENT ON TABLE "INTERCLOUD"."RESULT_TRACK" is 'Tracks the results of requests.';
/
COMMENT ON COLUMN RESULT_TRACK.ID IS 'The request ID';
COMMENT ON COLUMN RESULT_TRACK.TARGET_CLOUD IS 'The target cloud';
COMMENT ON COLUMN RESULT_TRACK.RESULT IS 'The result message';
COMMENT ON COLUMN RESULT_TRACK.LAST_UPDATE IS 'Last update time of the record, auto updated';
/

/* Authentication Table */
CREATE TABLE AUTHENTICATION 
   (	
   ID NUMBER NOT NULL ENABLE, 
   CHALLENGE VARCHAR2(200 BYTE) NOT NULL ENABLE, 
   CLOUD VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;
/
COMMENT ON TABLE "INTERCLOUD"."AUTHENTICATION" is 'For authenication use.';
/
COMMENT ON COLUMN "INTERCLOUD"."AUTHENTICATION"."ID" IS 'The request ID';
COMMENT ON COLUMN "INTERCLOUD"."AUTHENTICATION"."CHALLENGE" IS 'Challenge number';
COMMENT ON COLUMN "INTERCLOUD"."AUTHENTICATION"."CLOUD" IS 'The issuing cloud';
/
